begin;

create extension if not exists postgis;

create table if not exists public.locations (
  id bigint generated by default as identity primary key,
  canonical_address text not null,
  boro text not null,
  house_num text,
  street_name text not null,
  from_street text,
  to_street text,
  spec_loc text,
  location_key text not null,
  raw_geom_wkt text,
  geom geometry(MultiLineString, 4326),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint locations_boro_check check (boro in ('B', 'K', 'M', 'Q', 'R', 'S', 'X'))
);

create unique index if not exists locations_location_key_idx
  on public.locations (location_key);

create index if not exists locations_street_lookup_idx
  on public.locations (boro, street_name, from_street, to_street);

create index if not exists locations_house_lookup_idx
  on public.locations (boro, street_name, house_num);

create index if not exists locations_canonical_address_idx
  on public.locations (canonical_address);

create index if not exists locations_geom_gix
  on public.locations
  using gist (geom);

create table if not exists public.incidents (
  id bigint generated by default as identity primary key,
  location_id bigint not null references public.locations(id) on delete cascade,
  external_id text not null,
  dataset_name text not null default 'street_pothole_work_orders_closed',
  source text,
  initiated_by text,
  reported_at date not null,
  closed_at date,
  status text not null default 'closed',
  raw_house_num text,
  raw_street_name text,
  raw_from_street text,
  raw_to_street text,
  raw_spec_loc text,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint incidents_external_id_unique unique (external_id),
  constraint incidents_status_check check (status in ('open', 'closed', 'unknown')),
  constraint incidents_date_order_check check (closed_at is null or closed_at >= reported_at)
);

create index if not exists incidents_location_reported_idx
  on public.incidents (location_id, reported_at);

create index if not exists incidents_reported_at_idx
  on public.incidents (reported_at);

create index if not exists incidents_closed_at_idx
  on public.incidents (closed_at);

create index if not exists incidents_source_idx
  on public.incidents (source);

create table if not exists public.incident_events (
  id bigint generated by default as identity primary key,
  incident_id bigint not null references public.incidents(id) on delete cascade,
  event_type text not null,
  event_at timestamptz not null,
  event_label text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint incident_events_type_check
    check (event_type in ('reported', 'inspected', 'repaired', 'closed', 'claimed_incident', 'other'))
);

create index if not exists incident_events_incident_timeline_idx
  on public.incident_events (incident_id, event_at);

create index if not exists incident_events_type_idx
  on public.incident_events (event_type, event_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists locations_set_updated_at on public.locations;
create trigger locations_set_updated_at
before update on public.locations
for each row
execute function public.set_updated_at();

drop trigger if exists incidents_set_updated_at on public.incidents;
create trigger incidents_set_updated_at
before update on public.incidents
for each row
execute function public.set_updated_at();

create or replace view public.location_timelines as
select
  l.id as location_id,
  l.canonical_address,
  l.location_key,
  l.boro,
  l.house_num,
  l.street_name,
  l.from_street,
  l.to_street,
  i.id as incident_id,
  i.external_id,
  i.dataset_name,
  i.source,
  i.initiated_by,
  i.status,
  e.id as event_id,
  e.event_type,
  e.event_at,
  e.event_label,
  e.metadata
from public.locations l
join public.incidents i on i.location_id = l.id
join public.incident_events e on e.incident_id = i.id;

comment on table public.locations is
'Normalized address and street-segment records used to group city notice evidence.';

comment on table public.incidents is
'One row per city work order or related notice record tied to a normalized location.';

comment on table public.incident_events is
'Timeline events for each incident, such as reported and closed dates.';

comment on column public.locations.location_key is
'Deterministic grouping key such as B|1402|FULTON STREET|LEWIS AVENUE|SCHENECTADY AVENUE.';

commit;
